print("<!DOCTYPE html>\n")
print("<head><title>Akses dengan CGIHTTPRequestHandler</title></head>")
print("<body>")
print("<h3>Data diri</h3>")
print("<table><tr>")
print("<td>Nama</td>")
print("<td>:</td>")
print("<td>Afifah Ghaisani Imana</td>")
print("</tr>")
print("<tr>")
print("<td>Alamat tinggal</td>")
print("<td>:</td>")
print("<td>Griya Persada, Sawahan, Ngemplak</td>")
print("</tr>")
print("<tr>")
print("<td>Tempat, Tanggal Lahir</td>")
print("<td>:</td>")
print("<td>Ambarawa, 08 Februari</td>")
print("</tr>")
print("<tr>")
print("<td>Tempat Wisata Favorit</td>")
print("<td>:</td>")
print("<td>Bandungan</td>")
print("</tr>")
print("<tr>")
print("<td>Motto</td>")
print("<td>:</td>")
print("<td>Istiqomah</td>")
print("</tr>")
print("</tr></table>")



print("<pre>python -m http.server 8456</pre>")
print("</body></html>")
